model:
  image_encoder:
    model_name: "resnet50"
    frozen: true
  text_encoder:
    model_name: "bert-base-uncased"
    frozen: false
  fusion:
    hidden_size: 1024
    dropout: 0.5
  output_size: 1000

training:
  batch_size: 16
  epochs: 10
  learning_rate: 0.0001
  pin_memory: true
  no_of_workers: 0
  save_dir: "checkpoints/"

data:
  answer_vocab_path: "data/answer_to_idx.json"
  train:
    image_dir: "dataset/coco2014/images/train2014"
    questions_path: "dataset/coco2014/questions/OpenEnded_mscoco_train2014_questions.json"
    annotations_path: "dataset/coco2014/annotations/mscoco_train2014_annotations.json"
  val:
    image_dir: "dataset/coco2014/images/val2014"
    questions_path: "dataset/coco2014/questions/OpenEnded_mscoco_val2014_questions.json"
    annotations_path: "dataset/coco2014/annotations/mscoco_val2014_annotations.json"
  test:
    image_dir: "dataset/coco2014/images/test2014"
    questions_path: "dataset/coco2014/questions/OpenEnded_mscoco_test2015_questions.json"
    annotations_path: ""
